# coding: utf-8
"""
High-throughput random-AFM and SOC workflow for permanent-magnet screening.

This module is intended for large hexagonal, trigonal, and tetragonal magnetic
cells where symmetry-based MagneticStructureEnumerator can become impractical.
Instead of enumerating all symmetry-derived magnetic orderings, it calls
``random_afm_generator.MyCustomClass`` to create one FM configuration and
several random zero-net-moment AFM trial configurations. The resulting FM/AFM
energies can be used to estimate magnetic ordering stability and, with further
model assumptions, Curie-temperature trends.

Workflow summary:
    1. Generate one FM structure and multiple random AFM structures.
    2. Relax each ordering and run a static calculation.
    3. For FM-derived structures, add SOC calculations for a set of SAXIS
       directions.
    4. Store magnetic-ordering metadata and analysis records in the atomate
       database.

Notes:
    - The SOC energies from different SAXIS directions are the raw data used
      to estimate magnetic anisotropy.
    - Random AFM structures are generated by splitting each magnetic species
      into spin-up and spin-down groups. If any magnetic species has an odd
      site count, the generator doubles a cell axis so that a zero-net-moment
      AFM trial can be constructed.
    - Set random_afm_kwargs={"num_afm": 6, "seed": 123} when constructing
      MagneticOrderingsSOCWF to control how many AFM trials are generated and
      make the random choices reproducible.
    - Set standard_cell="primitive" or standard_cell="conventional" in get_wf()
      to choose the cell used for the FM SOC calculations.
    - save_orthorhombic_prim_magnetism_soc_20250109.py is the orthorhombic
      primitive-cell workflow; for orthorhombic systems the MAE comparison is
      typically reduced to the three principal SOC directions [100], [010],
      and [001].
    - num_samples controls angular sampling density, nbands_factor controls
      SOC NBANDS scaling, and kpoints_factor scales SOC reciprocal density.
    - Some crystal-system handling below is intentionally explicit because
      high-throughput MAE workflows often need a consistent axis convention.
"""

import os

import math
import numpy as np

from atomate.vasp.fireworks.core import OptimizeFW, StaticFW, SOCFW
from fireworks import Workflow, Firework
from atomate.vasp.powerups import (
    add_tags,
    add_additional_fields_to_taskdocs,
    add_wf_metadata,
    add_common_powerups,
)
from atomate.vasp.workflows.base.core import get_wf
from atomate.vasp.firetasks.parse_outputs import (
    MagneticDeformationToDB,
    MagneticOrderingsToDB,
)

from pymatgen.alchemy.materials import TransformedStructure

from atomate.utils.utils import get_logger

logger = get_logger(__name__)

from atomate.vasp.config import VASP_CMD, DB_FILE, ADD_WF_METADATA

from atomate.vasp.workflows.presets.scan import wf_scan_opt
from uuid import uuid4
from pymatgen.io.vasp.sets import MPRelaxSet
from pymatgen.core import Lattice, Structure
from pymatgen.analysis.magnetism.analyzer import (
    CollinearMagneticStructureAnalyzer,
)
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

try:
    from atomate.vasp.workflows.base.random_afm_generator import MyCustomClass
except ImportError:
    try:
        from random_afm_generator import MyCustomClass
    except ImportError:
        from random_afm import MyCustomClass

__author__ = "Matthew Horton"
__maintainer__ = "Matthew Horton"
__email__ = "mkhorton@lbl.gov"
__status__ = "Production"
__date__ = "March 2017"

__magnetic_deformation_wf_version__ = 1.2
__magnetic_ordering_wf_version__ = 2.0

module_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)))

def spherical_to_cartesian(theta, phi):
    """
    Convert spherical coordinates (theta, phi) to Cartesian coordinates (x, y, z).
    Assumes a unit sphere for simplicity.
    
    Parameters:
    theta (float): Polar angle in radians, measured from the positive z-axis downward to the xy-plane.
    phi (float): Azimuthal angle in radians, measured in the xy-plane from the positive x-axis.

    Returns:
    tuple: (x, y, z) Cartesian coordinates of the point on the unit sphere.
    """
    x = round(math.sin(theta) * math.cos(phi), 4)
    y = round(math.sin(theta) * math.sin(phi), 4)
    z = round(math.cos(theta), 4)
    return [x, y, z]

def get_saxis_from_crystal_type(crystal_type, num_samples=7):
    """Return unique SAXIS directions for SOC calculations.

    The angle grids are reduced using crystal symmetry assumptions. For
    tetragonal and hexagonal systems, only representative planes are sampled;
    lower-symmetry or unknown systems fall back to the xz-plane.
    """
    unique_saxis = {}

    if crystal_type == "tetragonal":
        # Define the sampling configurations
        configurations = [
            (np.linspace(0, 90, num_samples), [0]), # xz-plane
            ([90], np.linspace(0, 45, num_samples)), # xy-plane
            (np.linspace(0, 90, num_samples),[45]) # 110-plane
        ]
    elif crystal_type == "hexagonal":
        configurations = [
            (np.linspace(0, 90, num_samples), [0]), # xz-plane
            ([90], np.linspace(0, 60, num_samples)), # xy-plane
            (np.linspace(0, 90, num_samples),[60]) # 110-plane
        ]
    else:
        # warning that this is neither tetragonal nor hexagonal, we are going to sample xz plane only
        print(f"Warning: crystal type is {crystal_type}. Sampling xz-plane only.")

        configurations = [
            (np.linspace(0, 90, num_samples), [0]) # xz-plane
        ]

    # Loop through each configuration
    for theta_range, phi_range in configurations:
        for theta in theta_range:
            for phi in phi_range:
                sx, sy, sz = spherical_to_cartesian(math.radians(theta), math.radians(phi))
                if (sx, sy, sz) not in unique_saxis:
                    unique_saxis[(sx, sy, sz)] = [theta, phi, sx, sy, sz]

    return unique_saxis.values()

def get_standardized_structure_for_soc(structure, standard_cell="primitive", symprec=0.1):
    """Standardize the FM structure before SOC direction sampling.

    Args:
        structure: pymatgen Structure used for the FM SOC branch.
        standard_cell: "primitive" or "conventional".
        symprec: symmetry tolerance passed to SpacegroupAnalyzer.

    Returns:
        tuple: (standardized_structure, detected_crystal_system)
    """
    spa = SpacegroupAnalyzer(structure, symprec=symprec)
    if standard_cell == "primitive":
        return spa.get_primitive_standard_structure(), spa.get_crystal_system()
    if standard_cell == "conventional":
        return spa.get_conventional_standard_structure(), spa.get_crystal_system()
    raise ValueError(
        "standard_cell must be either 'primitive' or 'conventional', "
        f"not {standard_cell!r}."
    )

def get_wf_magnetic_deformation(structure, c=None, vis=None):
    """
    Minimal workflow to obtain magnetic deformation proxy, as
    defined by Bocarsly et al. 2017, doi: 10.1021/acs.chemmater.6b04729

    Args:
        structure: input structure, must be structure with magnetic
    elements, such that pymatgen will initalize ferromagnetic input by
    default -- see MPRelaxSet.yaml for list of default elements
        c: Workflow config dict, in the same format
    as in presets/core.py and elsewhere in atomate
        vis: A VaspInputSet to use for the first FW

    Returns: Workflow
    """

    if not structure.is_ordered:
        raise ValueError(
            "Please obtain an ordered approximation of the input structure."
        )

    structure = structure.get_primitive_structure(use_site_props=True)

    # using a uuid for book-keeping,
    # in a similar way to other workflows
    uuid = str(uuid4())

    c_defaults = {"vasp_cmd": VASP_CMD, "db_file": DB_FILE}
    if c:
        c.update(c_defaults)
    else:
        c = c_defaults

    wf = get_wf(structure, "magnetic_deformation.yaml", common_params=c, vis=vis)

    fw_analysis = Firework(
        MagneticDeformationToDB(
            db_file=DB_FILE, wf_uuid=uuid, to_db=c.get("to_db", True)
        ),
        name="MagneticDeformationToDB",
    )

    wf.append_wf(Workflow.from_Firework(fw_analysis), wf.leaf_fw_ids)

    wf = add_common_powerups(wf, c)

    if c.get("ADD_WF_METADATA", ADD_WF_METADATA):
        wf = add_wf_metadata(wf, structure)

    wf = add_additional_fields_to_taskdocs(
        wf,
        {
            "wf_meta": {
                "wf_uuid": uuid,
                "wf_name": "magnetic_deformation",
                "wf_version": __magnetic_deformation_wf_version__,
            }
        },
    )

    return wf


class MagneticOrderingsSOCWF:
    def __init__(
        self,
        structure,
        default_magmoms=None,
        strategies=("ferromagnetic", "antiferromagnetic"),
        automatic=True,
        truncate_by_symmetry=True,
        transformation_kwargs=None,
        random_afm_kwargs=None,
    ):
        """
        Build FM and random AFM trial structures for a large magnetic cell.

        The constructor intentionally bypasses MagneticStructureEnumerator.
        This is useful when the number of magnetic sites makes full symmetry
        enumeration too expensive or too restrictive. The random AFM generator
        returns structures with ``magmom`` site properties already assigned.

        Args:
            structure: input structure
            random_afm_kwargs: optional keyword arguments passed to
        random_afm_generator.MyCustomClass, for example {"num_afm": 6,
        "seed": 123}
        """

        self.uuid = str(uuid4())
        self.wf_meta = {
            "wf_uuid": self.uuid,
            "wf_name": self.__class__.__name__,
            "wf_version": __magnetic_ordering_wf_version__,
        }

        random_afm_kwargs = random_afm_kwargs or {}
        random_afm_generator = MyCustomClass(structure, **random_afm_kwargs)
        ordered_structures, magmom_list = random_afm_generator.get_fm_afm_struct()

        self.sanitized_structure = ordered_structures[0].copy()
        self.ordered_structures = [struct.copy() for struct in ordered_structures]
        self.ordered_structure_origins = ["fm"] + ["afm"] * (len(ordered_structures) - 1)
        self.input_index = None
        self.input_origin = None
        self.generated_magmoms = magmom_list

    def get_wf(
        self, scan=False, perform_bader=True, num_orderings_hard_limit=16, c=None, 
        num_samples=None, nbands_factor=None, kpoints_factor=None, updated_user_incar_settings=None,
        standard_cell="primitive", crystal_type_override=None
    ):
        """
        Retrieve the FireWorks workflow.

        Args:
            scan: if True, use the SCAN functional instead of GGA+U, since
        the SCAN functional has shown to have improved performance for
        magnetic systems in some cases
            perform_bader: if True, make sure the "bader" binary is in your
        path, will use Bader analysis to calculate atom-projected magnetic
        moments
            num_orderings_hard_limit: will make sure total number of magnetic
        orderings does not exceed this number even if there are extra orderings
        of equivalent symmetry
            c: additional config dict (as used elsewhere in atomate)
            standard_cell: choose "primitive" or "conventional" for the FM
        structure used in SOC calculations
            crystal_type_override: optionally override the detected crystal
        system used to choose SAXIS sampling directions

        Returns: FireWorks Workflow

        """

        nbands_factor = nbands_factor or 1
        kpoints_factor = kpoints_factor or 2
        num_samples = num_samples or 7

        c = c or {"VASP_CMD": VASP_CMD, "DB_FILE": DB_FILE}

        fws = []
        analysis_parents = []

        # trim total number of orderings (useful in high-throughput context)
        # this is somewhat course, better to reduce num_orderings kwarg and/or
        # change enumeration strategies
        ordered_structures = self.ordered_structures
        ordered_structure_origins = self.ordered_structure_origins

        def _add_metadata(structure):
            """
            For book-keeping, store useful metadata with the Structure
            object for later database ingestion including workflow
            version and a UUID for easier querying of all tasks generated
            from the workflow.

            Args:
                structure: Structure

            Returns: TransformedStructure
            """
            # this could be further improved by storing full transformation
            # history, but would require an improved transformation pipeline
            return TransformedStructure(
                structure, other_parameters={"wf_meta": self.wf_meta}
            )

        ordered_structures = [_add_metadata(struct) for struct in ordered_structures]

        if (
            num_orderings_hard_limit
            and len(self.ordered_structures) > num_orderings_hard_limit
        ):
            ordered_structures = self.ordered_structures[0:num_orderings_hard_limit]
            ordered_structure_origins = self.ordered_structure_origins[
                0:num_orderings_hard_limit
            ]
            logger.warning(
                "Number of ordered structures exceeds hard limit, "
                "removing last {} structures.".format(
                    len(self.ordered_structures) - len(ordered_structures)
                )
            )
            # always make sure input structure is included
            if self.input_index and self.input_index > num_orderings_hard_limit:
                ordered_structures.append(self.ordered_structures[self.input_index])
                ordered_structure_origins.append(
                    self.ordered_structure_origins[self.input_index]
                )

        # default incar settings
        user_incar_settings = {"ISYM": 0, "LASPH": True, "EDIFFG": -0.05}
        if scan:
            # currently, using SCAN relaxation as a static calculation also
            # since it is typically high quality enough, but want to make
            # sure we are also writing the AECCAR* files
            user_incar_settings.update({"LAECHG": True})
        if updated_user_incar_settings is not None:
            user_incar_settings.update(updated_user_incar_settings)

        c["user_incar_settings"] = user_incar_settings

        # Each magnetic ordering is first evaluated without SOC. The relaxed
        # and static energies are then used by MagneticOrderingsToDB to compare
        # FM/AFM stability.
        for idx, [ordered_structure, ordered_structure_origin] in enumerate(zip(ordered_structures, 
                                                                         ordered_structure_origins)):

            analyzer = CollinearMagneticStructureAnalyzer(ordered_structure)

            name = " ordering {} {} -".format(idx, analyzer.ordering.value)

            if ordered_structure_origin == 'fm':
                if isinstance(ordered_structure, TransformedStructure):
                    ordered_structure = ordered_structure.final_structure

                    logger.warning(
                        "Use final_structure of the TransformedStructure! "
                        )
                ordered_structure, crystal_type = get_standardized_structure_for_soc(
                    ordered_structure, standard_cell=standard_cell, symprec=0.1
                )
                if crystal_type_override is not None:
                    crystal_type = crystal_type_override

            if not scan:

                # Relaxation k-point density is intentionally fixed here for
                # consistency across high-throughput magnetic-ordering runs.
                vis = MPRelaxSet(
                    ordered_structure, user_incar_settings=user_incar_settings, user_kpoints_settings={"reciprocal_density": 64}
                )

                # relax
                fws.append(
                    OptimizeFW(
                        ordered_structure,
                        vasp_input_set=vis,
                        vasp_cmd=c["VASP_CMD"],
                        db_file=c["DB_FILE"],
                        max_force_threshold=0.05,
                        half_kpts_first_relax=False,
                        name=name + " optimize",
                    )
                )
                # StaticFW reuses the previous calculation location below.

                # static
                fws.append(
                    StaticFW(
                        ordered_structure,
                        vasp_cmd=c["VASP_CMD"],
                        db_file=c["DB_FILE"],
                        name=name + " static",
                        prev_calc_loc=True,
                        parents=fws[-1],
                    )
                )
                # SOC k-point density is set independently in the SOCFW block.

            else:

                # wf_scan_opt is just a single FireWork so can append it directly
                scan_fws = wf_scan_opt(ordered_structure, c=c).fws
                # change name for consistency with non-SCAN
                new_name = scan_fws[0].name.replace(
                    "structure optimization", name + " optimize"
                )
                scan_fws[0].name = new_name
                scan_fws[0].tasks[-1]["additional_fields"]["task_label"] = new_name
                fws += scan_fws

            analysis_parents.append(fws[-1])

            if ordered_structure_origin =='fm':

                logger.warning(
                    "Adding spin-orbit coupling calculations, "
                    "Before adding soc: {} fws.".format(len(fws))
                )

                # SOC calculations are only attached to the FM branch. The
                # energy differences between SAXIS directions are later used to
                # infer magnetic anisotropy.
                fm_parent = fws[-1]
                saxises = get_saxis_from_crystal_type(crystal_type, num_samples=num_samples)
                for saxis in saxises: 
                    saxis_str = "_".join([str(i_str) for i_str in saxis])

                    # defult user_kpoints_settings of reciprocal_density is 200, this part needs convergence test
                    reciprocal_density = 100

                    fws.append(
                        SOCFW(
                            magmom=None,
                            structure=ordered_structure,
                            db_file=c["DB_FILE"],
                            name=name + 'spin-orbit coupling ' + saxis_str,
                            parents=fm_parent,
                            saxis=saxis[2:],
                            nbands_factor=nbands_factor,
                            reciprocal_density=reciprocal_density*kpoints_factor
                        )
                    )
                    

        fw_analysis = Firework(
            MagneticOrderingsToDB(
                db_file=c["DB_FILE"],
                wf_uuid=self.uuid,
                auto_generated=False,
                name="MagneticOrderingsToDB",
                parent_structure=self.sanitized_structure,
                origins=ordered_structure_origins,
                input_index=self.input_index,
                perform_bader=perform_bader,
                scan=scan,
            ),
            name="Magnetic Orderings Analysis",
            parents=analysis_parents,
            spec={"_allow_fizzled_parents": True},
        )
        fws.append(fw_analysis)

        formula = self.sanitized_structure.composition.reduced_formula
        wf_name = "{} - magnetic orderings".format(formula)
        if scan:
            wf_name += " - SCAN"
        wf = Workflow(fws, name=wf_name)

        wf = add_additional_fields_to_taskdocs(wf, {"wf_meta": self.wf_meta})

        tag = "magnetic_orderings group: >>{}<<".format(self.uuid)
        wf = add_tags(wf, [tag, ordered_structure_origins])

        return wf


if __name__ == "__main__":

    # for trying workflows

    from fireworks import LaunchPad

    latt = Lattice.cubic(4.17)
    species = ["Ni", "O"]
    coords = [[0.00000, 0.00000, 0.00000], [0.50000, 0.50000, 0.50000]]
    NiO = Structure.from_spacegroup(225, latt, species, coords)

    wf_deformation = get_wf_magnetic_deformation(NiO)

    wf_orderings = MagneticOrderingsSOCWF(NiO).get_wf(num_samples=2,nbands_factor=2, kpoints_factor=2,
                                                      num_orderings_hard_limit=3)

    lpad = LaunchPad.auto_load()
    lpad.add_wf(wf_orderings)
    lpad.add_wf(wf_deformation)


#from fireworks import LaunchPad
#from pymatgen.ext.matproj import MPRester
#from atomate.vasp.workflows.base.magnetism_soc import get_wf_magnetic_deformation, MagneticOrderingsSOCWF

#vis = MPRester(endpoint='https://legacy.materialsproject.org/rest/v2/')
#struct = vis.get_structure_by_material_id("mp-2213")

#wf_deformation = get_wf_magnetic_deformation(struct)

#user_incar_settings = {"ISYM": 0, "LASPH": True, "EDIFFG": -0.05}
#wf_orderings = MagneticOrderingsSOCWF(struct).get_wf(num_samples=2,nbands_factor=2, kpoints_factor=2,
#                                                    num_orderings_hard_limit=3,updated_user_incar_settings={'ISMEAR': 0, 'SIGMA': 0.2})

#lpad = LaunchPad.auto_load()
#lpad.add_wf(wf_orderings)
#lpad.add_wf(wf_deformation)
